// Code generated by protoc-gen-go.
// source: IM.Customer.proto
// DO NOT EDIT!

/*
Package IM_Customer is a generated protocol buffer package.

It is generated from these files:
	IM.Customer.proto

It has these top-level messages:
	IMCustomerInfoReq
	IMCustomerInfoRsp
	IMCustomerChangeReceptionStatusReq
	IMCustomerChangeReceptionStatusRsp
	IMGetForwardingUserListReq
	IMGetForwardingUserListRsp
	IMCustomerForwardingReq
	IMCustomerForwardingRsp
	IMCustomerForwardingNotify
*/
package IM_Customer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_BaseDefine "../IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 使用user_id 查询该用户所在的客服号的信息,
// 若user_id 不是客服子号,则customer_list 为空
type IMCustomerInfoReq struct {
	// cmd is: 0x0c01
	ReqUserId        *uint32 `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	UserId           *uint32 `protobuf:"varint,2,req,name=user_id" json:"user_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMCustomerInfoReq) Reset()                    { *m = IMCustomerInfoReq{} }
func (m *IMCustomerInfoReq) String() string            { return proto.CompactTextString(m) }
func (*IMCustomerInfoReq) ProtoMessage()               {}
func (*IMCustomerInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IMCustomerInfoReq) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMCustomerInfoReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMCustomerInfoReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMCustomerInfoRsp struct {
	// cmd is: 0x0c02
	ReqUserId        *uint32                       `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	UserId           *uint32                       `protobuf:"varint,2,req,name=user_id" json:"user_id,omitempty"`
	ResultCode       *uint32                       `protobuf:"varint,3,opt,name=result_code" json:"result_code,omitempty"`
	CustomerList     []*IM_BaseDefine.CustomerInfo `protobuf:"bytes,4,rep,name=customer_list" json:"customer_list,omitempty"`
	AttachData       []byte                        `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *IMCustomerInfoRsp) Reset()                    { *m = IMCustomerInfoRsp{} }
func (m *IMCustomerInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*IMCustomerInfoRsp) ProtoMessage()               {}
func (*IMCustomerInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMCustomerInfoRsp) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMCustomerInfoRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMCustomerInfoRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMCustomerInfoRsp) GetCustomerList() []*IM_BaseDefine.CustomerInfo {
	if m != nil {
		return m.CustomerList
	}
	return nil
}

func (m *IMCustomerInfoRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMCustomerChangeReceptionStatusReq struct {
	// cmd is: 0x0c03
	ReqUserId        *uint32 `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	CustomerId       *uint32 `protobuf:"varint,2,opt,name=customer_id" json:"customer_id,omitempty"`
	Status           *uint32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	AttachData       []byte  `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMCustomerChangeReceptionStatusReq) Reset()         { *m = IMCustomerChangeReceptionStatusReq{} }
func (m *IMCustomerChangeReceptionStatusReq) String() string { return proto.CompactTextString(m) }
func (*IMCustomerChangeReceptionStatusReq) ProtoMessage()    {}
func (*IMCustomerChangeReceptionStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

func (m *IMCustomerChangeReceptionStatusReq) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMCustomerChangeReceptionStatusReq) GetCustomerId() uint32 {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return 0
}

func (m *IMCustomerChangeReceptionStatusReq) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *IMCustomerChangeReceptionStatusReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMCustomerChangeReceptionStatusRsp struct {
	// cmd is: 0x0c04
	ReqUserId        *uint32 `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,opt,name=result_code" json:"result_code,omitempty"`
	AttachData       []byte  `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMCustomerChangeReceptionStatusRsp) Reset()         { *m = IMCustomerChangeReceptionStatusRsp{} }
func (m *IMCustomerChangeReceptionStatusRsp) String() string { return proto.CompactTextString(m) }
func (*IMCustomerChangeReceptionStatusRsp) ProtoMessage()    {}
func (*IMCustomerChangeReceptionStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

func (m *IMCustomerChangeReceptionStatusRsp) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMCustomerChangeReceptionStatusRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMCustomerChangeReceptionStatusRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetForwardingUserListReq struct {
	// cmd is : 0x0c05
	ReqUserId        *uint32 `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	CustomerId       *uint32 `protobuf:"varint,2,opt,name=customer_id" json:"customer_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMGetForwardingUserListReq) Reset()                    { *m = IMGetForwardingUserListReq{} }
func (m *IMGetForwardingUserListReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetForwardingUserListReq) ProtoMessage()               {}
func (*IMGetForwardingUserListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IMGetForwardingUserListReq) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMGetForwardingUserListReq) GetCustomerId() uint32 {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return 0
}

func (m *IMGetForwardingUserListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetForwardingUserListRsp struct {
	// cmd is : 0x0c
	ReqUserId        *uint32                        `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	CustomerId       *uint32                        `protobuf:"varint,2,req,name=customer_id" json:"customer_id,omitempty"`
	ResultCode       *uint32                        `protobuf:"varint,3,opt,name=result_code" json:"result_code,omitempty"`
	SubUsersList     []*IM_BaseDefine.SubUserStatus `protobuf:"bytes,4,rep,name=sub_users_list" json:"sub_users_list,omitempty"`
	AttachData       []byte                         `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *IMGetForwardingUserListRsp) Reset()                    { *m = IMGetForwardingUserListRsp{} }
func (m *IMGetForwardingUserListRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetForwardingUserListRsp) ProtoMessage()               {}
func (*IMGetForwardingUserListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMGetForwardingUserListRsp) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMGetForwardingUserListRsp) GetCustomerId() uint32 {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return 0
}

func (m *IMGetForwardingUserListRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMGetForwardingUserListRsp) GetSubUsersList() []*IM_BaseDefine.SubUserStatus {
	if m != nil {
		return m.SubUsersList
	}
	return nil
}

func (m *IMGetForwardingUserListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMCustomerForwardingReq struct {
	ReqUserId        *uint32 `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	CustomerId       *uint32 `protobuf:"varint,2,opt,name=customer_id" json:"customer_id,omitempty"`
	FromId           *uint32 `protobuf:"varint,3,opt,name=from_id" json:"from_id,omitempty"`
	ToSubId          *uint32 `protobuf:"varint,4,opt,name=to_sub_id" json:"to_sub_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMCustomerForwardingReq) Reset()                    { *m = IMCustomerForwardingReq{} }
func (m *IMCustomerForwardingReq) String() string            { return proto.CompactTextString(m) }
func (*IMCustomerForwardingReq) ProtoMessage()               {}
func (*IMCustomerForwardingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMCustomerForwardingReq) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMCustomerForwardingReq) GetCustomerId() uint32 {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return 0
}

func (m *IMCustomerForwardingReq) GetFromId() uint32 {
	if m != nil && m.FromId != nil {
		return *m.FromId
	}
	return 0
}

func (m *IMCustomerForwardingReq) GetToSubId() uint32 {
	if m != nil && m.ToSubId != nil {
		return *m.ToSubId
	}
	return 0
}

func (m *IMCustomerForwardingReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMCustomerForwardingRsp struct {
	ReqUserId        *uint32 `protobuf:"varint,1,opt,name=req_user_id" json:"req_user_id,omitempty"`
	CustomerId       *int32  `protobuf:"varint,2,opt,name=customer_id" json:"customer_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,3,opt,name=result_code" json:"result_code,omitempty"`
	AttachFromId     *uint32 `protobuf:"varint,4,opt,name=attach_from_id" json:"attach_from_id,omitempty"`
	AttachToSubId    *uint32 `protobuf:"varint,5,opt,name=attach_to_sub_id" json:"attach_to_sub_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,15,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMCustomerForwardingRsp) Reset()                    { *m = IMCustomerForwardingRsp{} }
func (m *IMCustomerForwardingRsp) String() string            { return proto.CompactTextString(m) }
func (*IMCustomerForwardingRsp) ProtoMessage()               {}
func (*IMCustomerForwardingRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMCustomerForwardingRsp) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMCustomerForwardingRsp) GetCustomerId() int32 {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return 0
}

func (m *IMCustomerForwardingRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMCustomerForwardingRsp) GetAttachFromId() uint32 {
	if m != nil && m.AttachFromId != nil {
		return *m.AttachFromId
	}
	return 0
}

func (m *IMCustomerForwardingRsp) GetAttachToSubId() uint32 {
	if m != nil && m.AttachToSubId != nil {
		return *m.AttachToSubId
	}
	return 0
}

func (m *IMCustomerForwardingRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 转接成功后由服务端发给被转接的子账号, 若子账号在线账应该有提示
type IMCustomerForwardingNotify struct {
	// cmd is: 0x0c07
	FromId              *uint32 `protobuf:"varint,1,opt,name=from_id" json:"from_id,omitempty"`
	CustomerId          *uint32 `protobuf:"varint,2,opt,name=customer_id" json:"customer_id,omitempty"`
	ForwardingFromSubId *uint32 `protobuf:"varint,3,opt,name=forwarding_from_sub_id" json:"forwarding_from_sub_id,omitempty"`
	ForwardingToSubId   *uint32 `protobuf:"varint,4,opt,name=forwarding_to_sub_id" json:"forwarding_to_sub_id,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *IMCustomerForwardingNotify) Reset()                    { *m = IMCustomerForwardingNotify{} }
func (m *IMCustomerForwardingNotify) String() string            { return proto.CompactTextString(m) }
func (*IMCustomerForwardingNotify) ProtoMessage()               {}
func (*IMCustomerForwardingNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMCustomerForwardingNotify) GetFromId() uint32 {
	if m != nil && m.FromId != nil {
		return *m.FromId
	}
	return 0
}

func (m *IMCustomerForwardingNotify) GetCustomerId() uint32 {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return 0
}

func (m *IMCustomerForwardingNotify) GetForwardingFromSubId() uint32 {
	if m != nil && m.ForwardingFromSubId != nil {
		return *m.ForwardingFromSubId
	}
	return 0
}

func (m *IMCustomerForwardingNotify) GetForwardingToSubId() uint32 {
	if m != nil && m.ForwardingToSubId != nil {
		return *m.ForwardingToSubId
	}
	return 0
}

func init() {
	proto.RegisterType((*IMCustomerInfoReq)(nil), "IM.Customer.IMCustomerInfoReq")
	proto.RegisterType((*IMCustomerInfoRsp)(nil), "IM.Customer.IMCustomerInfoRsp")
	proto.RegisterType((*IMCustomerChangeReceptionStatusReq)(nil), "IM.Customer.IMCustomerChangeReceptionStatusReq")
	proto.RegisterType((*IMCustomerChangeReceptionStatusRsp)(nil), "IM.Customer.IMCustomerChangeReceptionStatusRsp")
	proto.RegisterType((*IMGetForwardingUserListReq)(nil), "IM.Customer.IMGetForwardingUserListReq")
	proto.RegisterType((*IMGetForwardingUserListRsp)(nil), "IM.Customer.IMGetForwardingUserListRsp")
	proto.RegisterType((*IMCustomerForwardingReq)(nil), "IM.Customer.IMCustomerForwardingReq")
	proto.RegisterType((*IMCustomerForwardingRsp)(nil), "IM.Customer.IMCustomerForwardingRsp")
	proto.RegisterType((*IMCustomerForwardingNotify)(nil), "IM.Customer.IMCustomerForwardingNotify")
}

func init() { proto.RegisterFile("IM.Customer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x94, 0x4f, 0xaf, 0xd2, 0x40,
	0x14, 0xc5, 0x53, 0x78, 0xcf, 0x17, 0x6f, 0x2d, 0xf8, 0x5a, 0xf3, 0x68, 0x80, 0x98, 0x86, 0x55,
	0x57, 0x5d, 0x10, 0x3f, 0x01, 0x18, 0xb5, 0x89, 0xb0, 0x80, 0xb8, 0x72, 0xd1, 0x0c, 0xed, 0x14,
	0xc6, 0x40, 0x07, 0x66, 0x6e, 0x63, 0x4c, 0x5c, 0xf8, 0x2d, 0x5c, 0xba, 0xf3, 0x73, 0x9a, 0xfe,
	0x81, 0x16, 0xe8, 0xa8, 0x6c, 0x4f, 0xe7, 0x9e, 0xf3, 0xbb, 0xe7, 0x26, 0x85, 0x47, 0x7f, 0xe6,
	0x4d, 0x53, 0x89, 0x7c, 0x47, 0x85, 0xb7, 0x17, 0x1c, 0xb9, 0xa9, 0xd7, 0xa4, 0xbe, 0xe5, 0xcf,
	0xbc, 0x09, 0x91, 0xf4, 0x2d, 0x8d, 0x59, 0x42, 0x8b, 0x17, 0xa3, 0x79, 0x36, 0x76, 0x7c, 0xe2,
	0x27, 0x31, 0x5f, 0xd0, 0x83, 0x69, 0x81, 0x2e, 0xe8, 0x21, 0x48, 0x25, 0x15, 0x01, 0x8b, 0x6c,
	0xcd, 0x69, 0xb9, 0x86, 0xd9, 0x85, 0x87, 0xa3, 0xd0, 0xca, 0x05, 0x0b, 0x74, 0x82, 0x48, 0xc2,
	0x4d, 0x10, 0x11, 0x24, 0x76, 0xd7, 0xd1, 0xdc, 0x17, 0xa3, 0x9f, 0xda, 0x95, 0xa1, 0xdc, 0xff,
	0xbf, 0xa1, 0xa0, 0x32, 0xdd, 0x62, 0x10, 0xf2, 0x88, 0xda, 0x6d, 0x47, 0x73, 0x0d, 0x73, 0x0c,
	0x46, 0x58, 0xba, 0x05, 0x5b, 0x26, 0xd1, 0xbe, 0x73, 0xda, 0xae, 0x3e, 0x1e, 0x78, 0xe7, 0xdb,
	0xd4, 0x13, 0x9b, 0xc9, 0x24, 0x8c, 0x2a, 0xb0, 0xe9, 0x86, 0x24, 0x6b, 0xba, 0xa0, 0x21, 0xdd,
	0x23, 0xe3, 0xc9, 0x12, 0x09, 0xa6, 0x52, 0xb9, 0xba, 0x05, 0xfa, 0x89, 0x21, 0xa7, 0xcd, 0xc0,
	0x3a, 0xf0, 0x4c, 0xe6, 0x63, 0x25, 0x68, 0x63, 0x68, 0xf8, 0xef, 0x50, 0x55, 0x3d, 0x17, 0x6d,
	0xb4, 0xd4, 0x21, 0x9f, 0xa1, 0xef, 0xcf, 0xde, 0x53, 0x7c, 0xc7, 0xc5, 0x57, 0x22, 0x22, 0x96,
	0xac, 0x3f, 0x49, 0x2a, 0x3e, 0x32, 0x89, 0xb7, 0x6d, 0xd4, 0x68, 0xfe, 0x5b, 0x53, 0xbb, 0xff,
	0x05, 0xfd, 0xdc, 0x5d, 0x79, 0xdd, 0x37, 0xd0, 0x91, 0xe9, 0x2a, 0x1f, 0x97, 0xf5, 0xf3, 0x0e,
	0x2f, 0xce, 0xbb, 0x4c, 0x57, 0x59, 0x6a, 0x51, 0x59, 0x33, 0xe8, 0x77, 0xe8, 0x55, 0x55, 0x57,
	0xb0, 0xb7, 0x55, 0xd0, 0x85, 0x87, 0x58, 0xf0, 0x5d, 0x26, 0x14, 0x80, 0x8f, 0xf0, 0x1c, 0x79,
	0x90, 0x31, 0xb2, 0xc8, 0xbe, 0x53, 0xd7, 0xf4, 0x4b, 0x53, 0xc4, 0x37, 0x75, 0xa4, 0x35, 0xc7,
	0xdf, 0x37, 0x77, 0xf4, 0x04, 0x9d, 0x32, 0xef, 0x88, 0x56, 0x70, 0xd8, 0xf0, 0xb2, 0xd4, 0x2b,
	0xc2, 0x7b, 0x35, 0xe1, 0x8f, 0xfc, 0x90, 0xd7, 0x84, 0x73, 0x8e, 0x2c, 0xfe, 0x56, 0xdf, 0x5c,
	0x09, 0x68, 0x98, 0xaf, 0xe1, 0x29, 0x3e, 0x4d, 0x16, 0x3c, 0x65, 0x72, 0xc1, 0x3a, 0x84, 0x57,
	0xb5, 0xef, 0x17, 0xcd, 0x4d, 0x06, 0xd0, 0x0b, 0xf9, 0xce, 0x8b, 0x78, 0xb2, 0xfe, 0xc2, 0x88,
	0x87, 0x58, 0xfc, 0x84, 0x56, 0x69, 0xfc, 0xa1, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x6f,
	0x60, 0xf9, 0xbf, 0x04, 0x00, 0x00,
}
