// Code generated by protoc-gen-go.
// source: IM.Other.proto
// DO NOT EDIT!

/*
Package IM_Other is a generated protocol buffer package.

It is generated from these files:
	IM.Other.proto

It has these top-level messages:
	IMHeartBeat
	IMKickUserReq
	IMKickUserResp
*/
package IM_Other

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IMHeartBeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMHeartBeat) Reset()                    { *m = IMHeartBeat{} }
func (m *IMHeartBeat) String() string            { return proto.CompactTextString(m) }
func (*IMHeartBeat) ProtoMessage()               {}
func (*IMHeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type IMKickUserReq struct {
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMKickUserReq) Reset()                    { *m = IMKickUserReq{} }
func (m *IMKickUserReq) String() string            { return proto.CompactTextString(m) }
func (*IMKickUserReq) ProtoMessage()               {}
func (*IMKickUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMKickUserReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type IMKickUserResp struct {
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	ReturnCode       *uint32 `protobuf:"varint,2,req,name=return_code" json:"return_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMKickUserResp) Reset()                    { *m = IMKickUserResp{} }
func (m *IMKickUserResp) String() string            { return proto.CompactTextString(m) }
func (*IMKickUserResp) ProtoMessage()               {}
func (*IMKickUserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMKickUserResp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMKickUserResp) GetReturnCode() uint32 {
	if m != nil && m.ReturnCode != nil {
		return *m.ReturnCode
	}
	return 0
}

func init() {
	proto.RegisterType((*IMHeartBeat)(nil), "IM.Other.IMHeartBeat")
	proto.RegisterType((*IMKickUserReq)(nil), "IM.Other.IMKickUserReq")
	proto.RegisterType((*IMKickUserResp)(nil), "IM.Other.IMKickUserResp")
}

func init() { proto.RegisterFile("IM.Other.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xf3, 0xf4, 0xd5, 0xf3,
	0x2f, 0xc9, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x78,
	0xb9, 0xb8, 0x3d, 0x7d, 0x3d, 0x52, 0x13, 0x8b, 0x4a, 0x9c, 0x52, 0x13, 0x4b, 0x94, 0x14, 0xb8,
	0x78, 0x3d, 0x7d, 0xbd, 0x33, 0x93, 0xb3, 0x43, 0x8b, 0x53, 0x8b, 0x82, 0x52, 0x0b, 0x85, 0xf8,
	0xb9, 0xd8, 0x4b, 0x8b, 0x53, 0x8b, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x78, 0x95,
	0xcc, 0x40, 0x86, 0x21, 0x54, 0x14, 0x17, 0x60, 0x28, 0x11, 0x12, 0xe6, 0xe2, 0x2e, 0x4a, 0x2d,
	0x29, 0x2d, 0xca, 0x8b, 0x4f, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x02, 0x09, 0x3a, 0x49, 0x73, 0x89,
	0x27, 0xe7, 0xe7, 0xea, 0xe5, 0xe6, 0xa7, 0x97, 0x66, 0x65, 0xa6, 0xea, 0x95, 0x94, 0x40, 0x9c,
	0x92, 0x54, 0x9a, 0xe6, 0xc1, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x38, 0xf0, 0x25, 0x9f, 0xa0,
	0x00, 0x00, 0x00,
}
