// Code generated by protoc-gen-go.
// source: IM.Message.proto
// DO NOT EDIT!

/*
Package IM_Message is a generated protocol buffer package.

It is generated from these files:
	IM.Message.proto

It has these top-level messages:
	IMMsgData
	IMMsgDataAck
	IMMsgDataReadAck
	IMMsgDataReadNotify
	IMClientTimeReq
	IMClientTimeRsp
	IMUnreadMsgCntReq
	IMUnreadMsgCntRsp
	IMGetMsgListReq
	IMGetMsgListRsp
	IMGetLatestMsgIdReq
	IMGetLatestMsgIdRsp
	IMGetMsgByIdReq
	IMGetMsgByIdRsp
	IMGetLostMsgListReq
	IMGetLostMsgListRsp
	IMDeleteMsgReq
	IMDeleteMsgRsp
*/
package IM_Message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_BaseDefine "../IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// service id  0x0003
type IMMsgData struct {
	// cmd id:        0x0301
	FromUserId       *uint32                `protobuf:"varint,1,req,name=from_user_id" json:"from_user_id,omitempty"`
	ToSessionId      *uint32                `protobuf:"varint,2,req,name=to_session_id" json:"to_session_id,omitempty"`
	MsgId            *uint32                `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	CreateTime       *uint32                `protobuf:"varint,4,req,name=create_time" json:"create_time,omitempty"`
	MsgType          *IM_BaseDefine.MsgType `protobuf:"varint,5,req,name=msg_type,enum=IM.BaseDefine.MsgType" json:"msg_type,omitempty"`
	MsgData          []byte                 `protobuf:"bytes,6,req,name=msg_data" json:"msg_data,omitempty"`
	AttachData       []byte                 `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	MsgTypeEx        *uint32                `protobuf:"varint,7,opt,name=msg_type_ex" json:"msg_type_ex,omitempty"`
	FromSubId        *uint32                `protobuf:"varint,8,opt,name=from_sub_id" json:"from_sub_id,omitempty"`
	ToSubId          *uint32                `protobuf:"varint,9,opt,name=to_sub_id" json:"to_sub_id,omitempty"`
	AttachRetCode    *uint32                `protobuf:"varint,10,opt,name=attach_ret_code" json:"attach_ret_code,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *IMMsgData) Reset()                    { *m = IMMsgData{} }
func (m *IMMsgData) String() string            { return proto.CompactTextString(m) }
func (*IMMsgData) ProtoMessage()               {}
func (*IMMsgData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IMMsgData) GetFromUserId() uint32 {
	if m != nil && m.FromUserId != nil {
		return *m.FromUserId
	}
	return 0
}

func (m *IMMsgData) GetToSessionId() uint32 {
	if m != nil && m.ToSessionId != nil {
		return *m.ToSessionId
	}
	return 0
}

func (m *IMMsgData) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgData) GetCreateTime() uint32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *IMMsgData) GetMsgType() IM_BaseDefine.MsgType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return IM_BaseDefine.MsgType_MSG_TYPE_SINGLE_TEXT
}

func (m *IMMsgData) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *IMMsgData) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMMsgData) GetMsgTypeEx() uint32 {
	if m != nil && m.MsgTypeEx != nil {
		return *m.MsgTypeEx
	}
	return 0
}

func (m *IMMsgData) GetFromSubId() uint32 {
	if m != nil && m.FromSubId != nil {
		return *m.FromSubId
	}
	return 0
}

func (m *IMMsgData) GetToSubId() uint32 {
	if m != nil && m.ToSubId != nil {
		return *m.ToSubId
	}
	return 0
}

func (m *IMMsgData) GetAttachRetCode() uint32 {
	if m != nil && m.AttachRetCode != nil {
		return *m.AttachRetCode
	}
	return 0
}

type IMMsgDataAck struct {
	// cmd id:        0x0302
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,5,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	FromSubId        *uint32                    `protobuf:"varint,6,opt,name=from_sub_id" json:"from_sub_id,omitempty"`
	ToSubId          *uint32                    `protobuf:"varint,7,opt,name=to_sub_id" json:"to_sub_id,omitempty"`
	RetCode          *uint32                    `protobuf:"varint,8,opt,name=ret_code" json:"ret_code,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataAck) Reset()                    { *m = IMMsgDataAck{} }
func (m *IMMsgDataAck) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataAck) ProtoMessage()               {}
func (*IMMsgDataAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMMsgDataAck) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataAck) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMMsgDataAck) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

func (m *IMMsgDataAck) GetFromSubId() uint32 {
	if m != nil && m.FromSubId != nil {
		return *m.FromSubId
	}
	return 0
}

func (m *IMMsgDataAck) GetToSubId() uint32 {
	if m != nil && m.ToSubId != nil {
		return *m.ToSubId
	}
	return 0
}

func (m *IMMsgDataAck) GetRetCode() uint32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

type IMMsgDataReadAck struct {
	// cmd id:        0x0303
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,5,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	FromSubId        *uint32                    `protobuf:"varint,6,opt,name=from_sub_id" json:"from_sub_id,omitempty"`
	ToSubId          *uint32                    `protobuf:"varint,7,opt,name=to_sub_id" json:"to_sub_id,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataReadAck) Reset()                    { *m = IMMsgDataReadAck{} }
func (m *IMMsgDataReadAck) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataReadAck) ProtoMessage()               {}
func (*IMMsgDataReadAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMMsgDataReadAck) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMMsgDataReadAck) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

func (m *IMMsgDataReadAck) GetFromSubId() uint32 {
	if m != nil && m.FromSubId != nil {
		return *m.FromSubId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetToSubId() uint32 {
	if m != nil && m.ToSubId != nil {
		return *m.ToSubId
	}
	return 0
}

type IMMsgDataReadNotify struct {
	// cmd id:        0x0304
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,5,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	FromSubId        *uint32                    `protobuf:"varint,6,opt,name=from_sub_id" json:"from_sub_id,omitempty"`
	ToSubId          *uint32                    `protobuf:"varint,7,opt,name=to_sub_id" json:"to_sub_id,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataReadNotify) Reset()                    { *m = IMMsgDataReadNotify{} }
func (m *IMMsgDataReadNotify) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataReadNotify) ProtoMessage()               {}
func (*IMMsgDataReadNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMMsgDataReadNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMMsgDataReadNotify) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetFromSubId() uint32 {
	if m != nil && m.FromSubId != nil {
		return *m.FromSubId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetToSubId() uint32 {
	if m != nil && m.ToSubId != nil {
		return *m.ToSubId
	}
	return 0
}

type IMClientTimeReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMClientTimeReq) Reset()                    { *m = IMClientTimeReq{} }
func (m *IMClientTimeReq) String() string            { return proto.CompactTextString(m) }
func (*IMClientTimeReq) ProtoMessage()               {}
func (*IMClientTimeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type IMClientTimeRsp struct {
	// cmd id:        0x0306
	ServerTime       *uint32 `protobuf:"varint,1,req,name=server_time" json:"server_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMClientTimeRsp) Reset()                    { *m = IMClientTimeRsp{} }
func (m *IMClientTimeRsp) String() string            { return proto.CompactTextString(m) }
func (*IMClientTimeRsp) ProtoMessage()               {}
func (*IMClientTimeRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMClientTimeRsp) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

type IMUnreadMsgCntReq struct {
	// cmd id:        0x0307
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	ReqSubId         *uint32 `protobuf:"varint,2,opt,name=req_sub_id" json:"req_sub_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMUnreadMsgCntReq) Reset()                    { *m = IMUnreadMsgCntReq{} }
func (m *IMUnreadMsgCntReq) String() string            { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntReq) ProtoMessage()               {}
func (*IMUnreadMsgCntReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMUnreadMsgCntReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMUnreadMsgCntReq) GetReqSubId() uint32 {
	if m != nil && m.ReqSubId != nil {
		return *m.ReqSubId
	}
	return 0
}

type IMUnreadMsgCntRsp struct {
	// cmd id:        0x0308
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	TotalCnt         *uint32                     `protobuf:"varint,2,req,name=total_cnt" json:"total_cnt,omitempty"`
	UnreadinfoList   []*IM_BaseDefine.UnreadInfo `protobuf:"bytes,3,rep,name=unreadinfo_list" json:"unreadinfo_list,omitempty"`
	AttachData       []byte                      `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMUnreadMsgCntRsp) Reset()                    { *m = IMUnreadMsgCntRsp{} }
func (m *IMUnreadMsgCntRsp) String() string            { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntRsp) ProtoMessage()               {}
func (*IMUnreadMsgCntRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMUnreadMsgCntRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetTotalCnt() uint32 {
	if m != nil && m.TotalCnt != nil {
		return *m.TotalCnt
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetUnreadinfoList() []*IM_BaseDefine.UnreadInfo {
	if m != nil {
		return m.UnreadinfoList
	}
	return nil
}

func (m *IMUnreadMsgCntRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgListReq struct {
	// cmd id:        0x0309
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgIdBegin       *uint32                    `protobuf:"varint,4,req,name=msg_id_begin" json:"msg_id_begin,omitempty"`
	MsgCnt           *uint32                    `protobuf:"varint,5,req,name=msg_cnt" json:"msg_cnt,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,6,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgListReq) Reset()                    { *m = IMGetMsgListReq{} }
func (m *IMGetMsgListReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgListReq) ProtoMessage()               {}
func (*IMGetMsgListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMGetMsgListReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgListReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgListReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgIdBegin() uint32 {
	if m != nil && m.MsgIdBegin != nil {
		return *m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgCnt() uint32 {
	if m != nil && m.MsgCnt != nil {
		return *m.MsgCnt
	}
	return 0
}

func (m *IMGetMsgListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMGetMsgListReq) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

// 对于群而言，如果消息数目返回的数值小于请求的cnt,则表示群的消息能拉取的到头了，更早的消息没有权限拉取。
// 如果msg_cnt 和 msg_id_begin计算得到的最早消息id与实际返回的最早消息id不一致，说明服务器消息有缺失，需要
// 客户端做一个缺失标记，避免下次再次拉取。
type IMGetMsgListRsp struct {
	// cmd id:        0x030a
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgIdBegin       *uint32                    `protobuf:"varint,4,req,name=msg_id_begin" json:"msg_id_begin,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo   `protobuf:"bytes,5,rep,name=msg_list" json:"msg_list,omitempty"`
	LastReadMsgId    *uint32                    `protobuf:"varint,6,opt,name=last_read_msg_id" json:"last_read_msg_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,7,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgListRsp) Reset()                    { *m = IMGetMsgListRsp{} }
func (m *IMGetMsgListRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgListRsp) ProtoMessage()               {}
func (*IMGetMsgListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMGetMsgListRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgListRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgIdBegin() uint32 {
	if m != nil && m.MsgIdBegin != nil {
		return *m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgListRsp) GetLastReadMsgId() uint32 {
	if m != nil && m.LastReadMsgId != nil {
		return *m.LastReadMsgId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMGetMsgListRsp) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

type IMGetLatestMsgIdReq struct {
	// cmd id:         0x030b
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,4,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetLatestMsgIdReq) Reset()                    { *m = IMGetLatestMsgIdReq{} }
func (m *IMGetLatestMsgIdReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdReq) ProtoMessage()               {}
func (*IMGetLatestMsgIdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMGetLatestMsgIdReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetLatestMsgIdReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMGetLatestMsgIdReq) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

type IMGetLatestMsgIdRsp struct {
	// cmd id:        0x030c
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	LatestMsgId      *uint32                    `protobuf:"varint,4,req,name=latest_msg_id" json:"latest_msg_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,5,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetLatestMsgIdRsp) Reset()                    { *m = IMGetLatestMsgIdRsp{} }
func (m *IMGetLatestMsgIdRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdRsp) ProtoMessage()               {}
func (*IMGetLatestMsgIdRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMGetLatestMsgIdRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetLatestMsgIdRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetLatestMsgId() uint32 {
	if m != nil && m.LatestMsgId != nil {
		return *m.LatestMsgId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMGetLatestMsgIdRsp) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

type IMGetMsgByIdReq struct {
	// cmd id:         0x030d
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgIdList        []uint32                   `protobuf:"varint,4,rep,name=msg_id_list" json:"msg_id_list,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,5,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgByIdReq) Reset()                    { *m = IMGetMsgByIdReq{} }
func (m *IMGetMsgByIdReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgByIdReq) ProtoMessage()               {}
func (*IMGetMsgByIdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IMGetMsgByIdReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgByIdReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetMsgIdList() []uint32 {
	if m != nil {
		return m.MsgIdList
	}
	return nil
}

func (m *IMGetMsgByIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMGetMsgByIdReq) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

type IMGetMsgByIdRsp struct {
	// cmd id:        0x030e
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo   `protobuf:"bytes,4,rep,name=msg_list" json:"msg_list,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	SessionTypeEx    *uint32                    `protobuf:"varint,5,opt,name=session_type_ex" json:"session_type_ex,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgByIdRsp) Reset()                    { *m = IMGetMsgByIdRsp{} }
func (m *IMGetMsgByIdRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgByIdRsp) ProtoMessage()               {}
func (*IMGetMsgByIdRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IMGetMsgByIdRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgByIdRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgByIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func (m *IMGetMsgByIdRsp) GetSessionTypeEx() uint32 {
	if m != nil && m.SessionTypeEx != nil {
		return *m.SessionTypeEx
	}
	return 0
}

type IMGetLostMsgListReq struct {
	// cmd id:       0x030f
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	MsgAckList       []*IM_BaseDefine.MsgAckType `protobuf:"bytes,2,rep,name=msg_ack_list" json:"msg_ack_list,omitempty"`
	AttachData       []byte                      `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMGetLostMsgListReq) Reset()                    { *m = IMGetLostMsgListReq{} }
func (m *IMGetLostMsgListReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetLostMsgListReq) ProtoMessage()               {}
func (*IMGetLostMsgListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IMGetLostMsgListReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLostMsgListReq) GetMsgAckList() []*IM_BaseDefine.MsgAckType {
	if m != nil {
		return m.MsgAckList
	}
	return nil
}

func (m *IMGetLostMsgListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLostMsgListRsp struct {
	// cmd id:       0x0310
	UserId           *uint32                  `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo `protobuf:"bytes,2,rep,name=msg_list" json:"msg_list,omitempty"`
	AttachData       []byte                   `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *IMGetLostMsgListRsp) Reset()                    { *m = IMGetLostMsgListRsp{} }
func (m *IMGetLostMsgListRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetLostMsgListRsp) ProtoMessage()               {}
func (*IMGetLostMsgListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IMGetLostMsgListRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLostMsgListRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetLostMsgListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDeleteMsgReq struct {
	// cmd is:       0x0311
	ReqUserId        *uint32 `protobuf:"varint,1,req,name=req_user_id" json:"req_user_id,omitempty"`
	FromUserId       *uint32 `protobuf:"varint,2,req,name=from_user_id" json:"from_user_id,omitempty"`
	ToUserId         *uint32 `protobuf:"varint,3,req,name=to_user_id" json:"to_user_id,omitempty"`
	MsgId            *uint32 `protobuf:"varint,4,req,name=msg_id" json:"msg_id,omitempty"`
	Type             *uint32 `protobuf:"varint,5,req,name=type" json:"type,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMDeleteMsgReq) Reset()                    { *m = IMDeleteMsgReq{} }
func (m *IMDeleteMsgReq) String() string            { return proto.CompactTextString(m) }
func (*IMDeleteMsgReq) ProtoMessage()               {}
func (*IMDeleteMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *IMDeleteMsgReq) GetReqUserId() uint32 {
	if m != nil && m.ReqUserId != nil {
		return *m.ReqUserId
	}
	return 0
}

func (m *IMDeleteMsgReq) GetFromUserId() uint32 {
	if m != nil && m.FromUserId != nil {
		return *m.FromUserId
	}
	return 0
}

func (m *IMDeleteMsgReq) GetToUserId() uint32 {
	if m != nil && m.ToUserId != nil {
		return *m.ToUserId
	}
	return 0
}

func (m *IMDeleteMsgReq) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMDeleteMsgReq) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *IMDeleteMsgReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDeleteMsgRsp struct {
	// cmd is:       0x0312
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMDeleteMsgRsp) Reset()                    { *m = IMDeleteMsgRsp{} }
func (m *IMDeleteMsgRsp) String() string            { return proto.CompactTextString(m) }
func (*IMDeleteMsgRsp) ProtoMessage()               {}
func (*IMDeleteMsgRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *IMDeleteMsgRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDeleteMsgRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *IMDeleteMsgRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func init() {
	proto.RegisterType((*IMMsgData)(nil), "IM.Message.IMMsgData")
	proto.RegisterType((*IMMsgDataAck)(nil), "IM.Message.IMMsgDataAck")
	proto.RegisterType((*IMMsgDataReadAck)(nil), "IM.Message.IMMsgDataReadAck")
	proto.RegisterType((*IMMsgDataReadNotify)(nil), "IM.Message.IMMsgDataReadNotify")
	proto.RegisterType((*IMClientTimeReq)(nil), "IM.Message.IMClientTimeReq")
	proto.RegisterType((*IMClientTimeRsp)(nil), "IM.Message.IMClientTimeRsp")
	proto.RegisterType((*IMUnreadMsgCntReq)(nil), "IM.Message.IMUnreadMsgCntReq")
	proto.RegisterType((*IMUnreadMsgCntRsp)(nil), "IM.Message.IMUnreadMsgCntRsp")
	proto.RegisterType((*IMGetMsgListReq)(nil), "IM.Message.IMGetMsgListReq")
	proto.RegisterType((*IMGetMsgListRsp)(nil), "IM.Message.IMGetMsgListRsp")
	proto.RegisterType((*IMGetLatestMsgIdReq)(nil), "IM.Message.IMGetLatestMsgIdReq")
	proto.RegisterType((*IMGetLatestMsgIdRsp)(nil), "IM.Message.IMGetLatestMsgIdRsp")
	proto.RegisterType((*IMGetMsgByIdReq)(nil), "IM.Message.IMGetMsgByIdReq")
	proto.RegisterType((*IMGetMsgByIdRsp)(nil), "IM.Message.IMGetMsgByIdRsp")
	proto.RegisterType((*IMGetLostMsgListReq)(nil), "IM.Message.IMGetLostMsgListReq")
	proto.RegisterType((*IMGetLostMsgListRsp)(nil), "IM.Message.IMGetLostMsgListRsp")
	proto.RegisterType((*IMDeleteMsgReq)(nil), "IM.Message.IMDeleteMsgReq")
	proto.RegisterType((*IMDeleteMsgRsp)(nil), "IM.Message.IMDeleteMsgRsp")
}

func init() { proto.RegisterFile("IM.Message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x96, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0x65, 0xe7, 0x4f, 0xdb, 0x69, 0x1a, 0xa7, 0x4e, 0xfb, 0xab, 0x7f, 0xe5, 0x62, 0xf9,
	0x80, 0x72, 0x0a, 0xa8, 0x6f, 0xd0, 0x3f, 0xa2, 0x58, 0xea, 0x72, 0x28, 0xe5, 0x6c, 0x6d, 0x9d,
	0x89, 0x31, 0x75, 0xec, 0xd4, 0xbb, 0x41, 0xe4, 0x86, 0x10, 0x4f, 0xc1, 0x2b, 0x70, 0xe2, 0x8a,
	0x84, 0xc4, 0x91, 0xc7, 0xe1, 0x11, 0xd0, 0xee, 0xda, 0x21, 0x71, 0x96, 0xb6, 0x39, 0xe4, 0xd0,
	0x63, 0x26, 0xeb, 0xd9, 0xef, 0x67, 0xbe, 0xb3, 0xb3, 0x0b, 0x1d, 0x9f, 0xf4, 0x09, 0x32, 0x46,
	0x23, 0xec, 0x8f, 0xf3, 0x8c, 0x67, 0x36, 0xfc, 0x8d, 0x1c, 0x76, 0x7d, 0xd2, 0x3f, 0xa1, 0x0c,
	0xcf, 0x70, 0x18, 0xa7, 0xc5, 0x02, 0xef, 0xb3, 0x09, 0x5b, 0x3e, 0x21, 0x2c, 0x3a, 0xa3, 0x9c,
	0xda, 0x7b, 0xd0, 0x1a, 0xe6, 0xd9, 0x28, 0x98, 0x30, 0xcc, 0x83, 0x78, 0xe0, 0x18, 0xae, 0xd9,
	0xdb, 0xb1, 0xf7, 0x61, 0x87, 0x67, 0x01, 0x43, 0xc6, 0xe2, 0x2c, 0x15, 0x61, 0x53, 0x86, 0xdb,
	0xd0, 0x1c, 0xb1, 0x48, 0xfc, 0xae, 0xc9, 0xdf, 0x5d, 0xd8, 0x0e, 0x73, 0xa4, 0x1c, 0x03, 0x1e,
	0x8f, 0xd0, 0xa9, 0xcb, 0x60, 0x0f, 0x36, 0xc5, 0x22, 0x3e, 0x1d, 0xa3, 0xd3, 0x70, 0xcd, 0x5e,
	0xfb, 0xe8, 0xbf, 0xfe, 0xa2, 0x0e, 0xc2, 0xa2, 0xab, 0xe9, 0x18, 0xed, 0x8e, 0x5a, 0x39, 0xa0,
	0x9c, 0x3a, 0x4d, 0xd7, 0xec, 0xb5, 0x44, 0x42, 0xca, 0x39, 0x0d, 0xdf, 0xaa, 0xe0, 0x9e, 0x6b,
	0xa8, 0x60, 0x99, 0x30, 0xc0, 0x0f, 0xce, 0x86, 0x6b, 0xa8, 0xad, 0xa5, 0x6e, 0x36, 0xb9, 0x16,
	0x7a, 0x36, 0x65, 0x70, 0x17, 0xb6, 0x84, 0x6c, 0x15, 0xda, 0x92, 0xa1, 0x03, 0xb0, 0x8a, 0x8c,
	0x39, 0xf2, 0x20, 0xcc, 0x06, 0xe8, 0x80, 0xf8, 0xc3, 0xfb, 0x65, 0x40, 0x6b, 0x56, 0x86, 0xe3,
	0xf0, 0xc6, 0xb6, 0x60, 0x63, 0xb1, 0x08, 0x36, 0xc0, 0xbd, 0x15, 0x78, 0x0e, 0xad, 0x72, 0x8d,
	0x04, 0xae, 0x4b, 0xe0, 0xc3, 0x0a, 0xf0, 0x6b, 0xb5, 0x44, 0x42, 0x1f, 0x80, 0x35, 0xff, 0x85,
	0x20, 0x6a, 0xe8, 0x88, 0x9a, 0xcb, 0x44, 0x8a, 0xbc, 0x03, 0x9b, 0x33, 0x14, 0x89, 0xed, 0x7d,
	0x37, 0x44, 0x1f, 0x14, 0x28, 0x97, 0x48, 0x07, 0x8f, 0x08, 0xc7, 0xfb, 0x61, 0x40, 0x77, 0x41,
	0xfc, 0xab, 0x8c, 0xc7, 0xc3, 0xe9, 0xa3, 0xd1, 0xbf, 0x0b, 0x96, 0x4f, 0x4e, 0x93, 0x18, 0x53,
	0x7e, 0x15, 0x8f, 0xf0, 0x12, 0x6f, 0xbd, 0xa7, 0x95, 0x10, 0x1b, 0x8b, 0x6c, 0x0c, 0xf3, 0xf7,
	0x98, 0xab, 0x93, 0x22, 0x89, 0x3c, 0x02, 0xbb, 0x3e, 0x79, 0x93, 0xe6, 0x48, 0x07, 0x84, 0x45,
	0xa7, 0x29, 0xbf, 0xc4, 0xdb, 0x65, 0x6e, 0xed, 0x99, 0xb0, 0x01, 0x72, 0xbc, 0x2d, 0x95, 0x98,
	0x52, 0xc9, 0x47, 0x63, 0x29, 0x1f, 0x1b, 0x2f, 0xe7, 0x93, 0x0c, 0x9c, 0x26, 0x41, 0x98, 0xf2,
	0xa2, 0x8c, 0x47, 0x60, 0x4d, 0xe4, 0x67, 0x71, 0x3a, 0xcc, 0x82, 0x24, 0x66, 0xdc, 0xa9, 0xb9,
	0xb5, 0xde, 0xf6, 0xd1, 0xff, 0x95, 0xca, 0xa9, 0xe4, 0x7e, 0x3a, 0xcc, 0xb4, 0xb2, 0x84, 0x99,
	0x96, 0x4f, 0xce, 0x91, 0x13, 0x16, 0x5d, 0xc4, 0x4c, 0x0f, 0x54, 0x35, 0xc9, 0xbc, 0xd7, 0xa4,
	0x45, 0xeb, 0x95, 0xd5, 0x7b, 0xd0, 0x52, 0xd6, 0x07, 0xd7, 0x18, 0xc5, 0x69, 0x31, 0x7c, 0x2c,
	0xd8, 0x10, 0x51, 0x81, 0xd6, 0xf8, 0x77, 0xf5, 0x34, 0xa6, 0x4b, 0x7f, 0xbd, 0xdf, 0x55, 0xfd,
	0xba, 0x02, 0xae, 0x53, 0x7f, 0x31, 0x3c, 0xa5, 0x05, 0x0d, 0x69, 0x81, 0x66, 0x78, 0xca, 0xfa,
	0x3b, 0xd0, 0x49, 0x28, 0xe3, 0x81, 0x30, 0x24, 0x28, 0x0e, 0x41, 0xb3, 0xec, 0xdc, 0x07, 0x21,
	0xab, 0xfe, 0xfd, 0x22, 0xcf, 0xdf, 0x39, 0xf2, 0x0b, 0xca, 0x91, 0x09, 0x70, 0x7f, 0xb0, 0x46,
	0xdb, 0x1e, 0x2a, 0xae, 0x2e, 0xc5, 0x7d, 0xd3, 0x89, 0x5b, 0x9f, 0x27, 0xfb, 0xb0, 0x93, 0xc8,
	0x8d, 0xca, 0x82, 0xd6, 0x57, 0xd2, 0x2c, 0x07, 0x87, 0xf7, 0x75, 0xae, 0x87, 0x4e, 0xa6, 0xeb,
	0x2e, 0x66, 0xd1, 0x43, 0xb2, 0x61, 0xea, 0x6e, 0x6d, 0x65, 0xb5, 0x3f, 0xab, 0x6a, 0xd7, 0x57,
	0xdd, 0xf9, 0xde, 0xae, 0xdf, 0xd9, 0xdb, 0xab, 0x21, 0x24, 0x65, 0x8f, 0x64, 0xec, 0xce, 0xb9,
	0xf3, 0x4c, 0x9d, 0x38, 0x1a, 0xde, 0x28, 0x0d, 0xa6, 0x76, 0xc4, 0x11, 0x16, 0x1d, 0x87, 0x37,
	0x12, 0x42, 0x3b, 0xe2, 0x50, 0xb3, 0x9b, 0xae, 0x66, 0xf3, 0xb4, 0xe6, 0xca, 0xb4, 0xde, 0x27,
	0x03, 0xda, 0x3e, 0x39, 0xc3, 0x04, 0x39, 0x12, 0x16, 0x09, 0xa0, 0x2e, 0x6c, 0x8b, 0x99, 0xbf,
	0xb8, 0x4d, 0xf5, 0xfd, 0x66, 0x96, 0x77, 0x25, 0xcf, 0x66, 0xb1, 0x5a, 0xe5, 0xae, 0x54, 0x5d,
	0xdd, 0x82, 0xfa, 0xec, 0x8d, 0xa6, 0xef, 0x1a, 0xef, 0xc5, 0xa2, 0x06, 0x1d, 0x66, 0x1b, 0x9a,
	0x39, 0xb2, 0x49, 0x52, 0x5e, 0x25, 0xba, 0x3c, 0x27, 0x4f, 0xe0, 0x20, 0xcc, 0x46, 0xfd, 0x51,
	0x16, 0x4d, 0xde, 0xc5, 0xd8, 0xe7, 0x5c, 0x3d, 0x45, 0xaf, 0x27, 0xc3, 0x97, 0xb5, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x4f, 0x29, 0x68, 0xff, 0xc3, 0x0a, 0x00, 0x00,
}
